### ISSUE TITLE
Adjust GroundTruthInit to initialize model_references of moving objects

### ISSUE THREAD

**Issue by ClemensLinnhoff** [OpenSimulationInterface/osi-sensor-model-packaging#107]
#### Describe the feature
Currently, the OSMP specification of the GounrdTruthInit parameter states:

```
Its purpose is to provide the model with a view of the static environment, for example the map, in OSI format.
```

I would like to extend this definition to also facilitate other non-changing attributes of other parts of the ground truth. The background is, that I would like to load 3D models specified by the model_reference field in the GroundTruth and also in the MovingObject data during the initialization of the FMU.

#### Describe the solution you would like
Simply extend the definition of what the GroundTruthInit entails from just "static environment" to all non-changing parts of the GroundTruth

#### Describe alternatives you have considered
Currently we are loading all 3D models in the first simulation time step. But this means, that we are not real-time capable in the first simulation time step.

**Comment by pmai** [comment]
To an extent this is already part of the discussion of what is considered static and what is considered dynamic information in OSI, which might lead to further specifications. And the problem itself is well understood.

The problem I would see with specifically model_reference (or other information) for MovingObject is that this would imply that the MovingObject itself is static information, and hence not changing (i.e. would never cease to exist, among other things). This would seem to be potentially confusing or contradictory and under-specified.

There might be ways of extending the current specification to handle this, however it is unclear to me if it would not be better to have a different mechanism for such information (especially since one probably does not care about the mapping MO <-> model, but rather just the information which models will be required at all).

In any case I think this might need more work on the OSI side of things, rather than just adjustments on the OSMP side of things...

**Comment by ClemensLinnhoff** [comment]
> that this would imply that the MovingObject itself is static information

I would not say that the MovingObject itself is static, but it contains constant information. And I don't see the problem in initializing this information. I made a PR as a basis for the further discussion on this: https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/pull/108
