### ISSUE TITLE
Update to new OSI release "Brave Brabham"

### ISSUE THREAD

**Issue by ghost** [OpenSimulationInterface/osi-sensor-model-packaging#14]
Is it possible to have an automatik update to the newest release? Or could you write a small wiki entry on how to update the repo for the other developer, please?

**Comment by pmai** [comment]
Automatic updates are not a good idea, since the code has to be checked/modified first for testing/integration. Each developer can update the referenced sub-module as usual (i.e. go to the open-simulation-interface sub-directory in examples and issue the usual git commands, then commit this change in the main directory); I'll add something to the wiki to that effect.
