### ISSUE TITLE
Cannot load FMU in dSpace Configuration Desk

### ISSUE THREAD

**Issue by stanislavbraun** [OpenSimulationInterface/osi-sensor-model-packaging#25]
After having built the OSMPCNetworkProxy using Visual Studio 2010, I'm not able to load the FMU into ConfigurationDesk 5.7.

The error thrown is:

`ConfigurationDesk Model Support:	Error	10:25:54.326	211,80: Could not process the FMU: Compressed size mismatch between central header(954) and local header(0) (0x1,11720)
`
After unpacking the FMU using 7zip and repacking, the FMU can be loaded into ConfigurationDesk.
Nevertheless, the following warnings occur:
`ConfigurationDesk FMU Support:	Warning	10:29:11.051	211,80: The variable 'address' has an unsupported type String. The variable will be ignored. (0x1,11720)`

`ConfigurationDesk FMU Support:	Warning	10:29:11.051	211,80: The variable 'port' has an unsupported type String. The variable will be ignored. (0x1,11720)`

**Comment by pmai** [comment]
The ZIP Error seems to be a bug in the C# Zip Library used by ConfigurationDesk (cf. http://community.sharpdevelop.net/forums/t/9055.aspx, it seems the library is checking local header sizes even if the flag indicating that the local header does not contain sizes is set, which runs against the ZIP Specification; this is likely to occur with tools that do streaming zip archive creation more than in the repackaging case, which is why the repackaging works as a work-around). This should be raised with dSpace, I think.

The warnings about string variables seem to be a further limitation of ConfigurationDesk (string variables and parameters are not an optional part of FMI 1.0/2.0). Since they are being ignored, the FMU will use the compiled in default values, e.g. you would have to change the defaults in the source directly. Again a bug should be filed against dSpace ConfigurationDesk IMHO, since string parameters are neither optional nor uncommon nowadays.

I'll add CMake variables for the defaults in a next release to aid reconfiguration of the defaults.

**Comment by ghost** [comment]
@pmai can you address these issues when you are in Padaborn this week, please?

**Comment by pmai** [comment]
@CarloVanDriestenBMW I'll see what I can do, but these issues should also be communicated via the dSpace support chain, otherwise I think they will get lost/less traction.

I've pushed PR #27 which should help working around this to a certain degree.

**Comment by pmai** [comment]
Closing issue since nothing left for OSMP to do.
