### ISSUE TITLE
What is the command to run OSMPDummySensor?

### ISSUE THREAD

**Issue by rp-applied** [OpenSimulationInterface/osi-sensor-model-packaging#39]
I'm building all of the files using CMakeList.txt in the examples directory and then building each example component independently. When I run `./OSMPDummySource.so` I get a segmentation fault . What is the command to run OSMPDummySensor?

Thanks

**Comment by pmai** [comment]
The build product for the example FMUs are the *.fmu files, which are OSMP-compliant FMUs. So in order to run them, you need an environment that is capable of running FMUs (see http://fmi-standard.org/ ). In addition, if you want the sensor fmu to do something, you need to connect it up to a relevant OSI SensorView source, i.e. either run it in an environment simulation that is capable of supporting OSI Sensor FMUs directly, or you can connect another FMU that provides OSI SensorView output to the sensor FMU in a "normal" FMU environment; e.g. you can connect up OSMPDummySource to OSMPDummySensor in any FMU simulation environment for initial testing. Or you can use the OSMPCNetworkProxy FMU to receive OSI input from a network socket and connect that to the Sensor FMU.

**Comment by rp-applied** [comment]
Thanks! Do you have any recommendations for a basic FMU I can use to connect the OSMPDummySensor and the OSMPDummySource to see data being visualized in the OSI-Visualizer? I am on Ubuntu. My eventual goal is to offer a sensor with the OSI format that you have created.

Thank you for the input!

**Comment by mshaheerm** [comment]
@rp-applied how can i build the examples with cmake and then further make each example? can you please help?
