### ISSUE TITLE
Cannot Build as mentioned in the wiki BUILD...

### ISSUE THREAD

**Issue by mshaheerm** [OpenSimulationInterface/osi-sensor-model-packaging#42]
![capture](https://user-images.githubusercontent.com/40594242/43761736-3a1849e6-9a26-11e8-9f1d-d704b505b638.JPG)
I am using win cmd promt and its throwing the error when i try to do the first step. how to fix it?

**Comment by pmai** [comment]
You seem to have downloaded the osi sensor model packaging directories, instead of cloning them with git. Hence git is complaining that you are not in a git repository. You need to clone the osi-sensor-model-packaging repository (using git clone, or via the GitHub Desktop Client, or some other git client). Then you can use git submodule to fetch the required submodule, etc.
