### ISSUE TITLE
Simulator Output to Osi packaging.

### ISSUE THREAD

**Issue by mshaheerm** [OpenSimulationInterface/osi-sensor-model-packaging#43]
I am working on CARLA and want to send them as in osi packaging. i did not understand the build of the examplesand i cant even build those examples. how to get started working with osi packaging?

**Comment by pmai** [comment]
Sorry, I don't know anything about CARLA, so I can't say anything about OSI support in CARLA (I don't think there is any at the moment). In order to work with the examples (see other issue about building), you will need at a minimum to have some environment that is capable of running FMUs. And then you will need to have an OSI source: For simple debugging purposes you can use the OSMPDummySource FMU as an OSI source and connect that to your sensor FMU in any FMI environment, but for actual use you will want to have a simulation environment capable of generating OSI data and running OSMP-style FMUs.

If you want to add OSI support to CARLA, you will need to implement support for FMI, and then the relevant support for OSMP-style FMUs and OSI. That will usually involve quite a bit of C and C++ system-level hacking.
